using System;
using System.Collections.Generic;

namespace NCDataMatch.Models
{
    public partial class IC_SALEOUT_B
    {
        public string BADVFEEFLAG { get; set; }
        public string BBARCODECLOSE { get; set; }
        public string BLENDOUTFLAG { get; set; }
        public string BONROADFLAG { get; set; }
        public string BRETURNPROFIT { get; set; }
        public string BSAFEPRICE { get; set; }
        public string BSAMPLE { get; set; }
        public string BSOURCELARGESS { get; set; }
        public string BTOU8RM { get; set; }
        public string BWASTAGEFLAG { get; set; }
        public string CASSCUSTID { get; set; }
        public string CASTUNITID { get; set; }
        public string CBODYTRANSTYPECODE { get; set; }
        public string CBODYWAREHOUSEID { get; set; }
        public string CCORRESPONDBID { get; set; }
        public string CCORRESPONDCODE { get; set; }
        public string CCORRESPONDHID { get; set; }
        public string CCORRESPONDROWNO { get; set; }
        public string CCORRESPONDTRANSTYPE { get; set; }
        public string CCORRESPONDTYPE { get; set; }
        public string CCOSTOBJECT { get; set; }
        public string CCURRENCYID { get; set; }
        public string CCUSTMATERIALID { get; set; }
        public string CDELIVERY_BBID { get; set; }
        public string CFANACEORGOID { get; set; }
        public string CFFILEID { get; set; }
        public string CFIRSTBILLBID { get; set; }
        public string CFIRSTBILLDATE { get; set; }
        public string CFIRSTBILLHID { get; set; }
        public string CFIRSTTRANSTYPE { get; set; }
        public string CFIRSTTYPE { get; set; }
        public string CGENERALBID { get; set; }
        public string CGENERALHID { get; set; }
        public string CGLOBALCURRENCYID { get; set; }
        public string CGROUPCURRENCYID { get; set; }
        public string CINVOICECUSTID { get; set; }
        public string CIOLIABILITYOID { get; set; }
        public string CIOLIABILITYVID { get; set; }
        public string CLIABILITYOID { get; set; }
        public string CLIABILITYVID { get; set; }
        public string CLOCATIONID { get; set; }
        public string CMATERIALOID { get; set; }
        public string CMATERIALVID { get; set; }
        public string CORIGAREAID { get; set; }
        public string CORIGCOUNTRYID { get; set; }
        public string CORIGCURRENCYID { get; set; }
        public string CORPOID { get; set; }
        public string CORPVID { get; set; }
        public string CPRODLINEID { get; set; }
        public string CPRODUCTORID { get; set; }
        public string CPROJECTID { get; set; }
        public string CQTUNITID { get; set; }
        public string CRECEIEVEID { get; set; }
        public string CRECEIVEAREAID { get; set; }
        public string CRECEIVEPOINTID { get; set; }
        public string CROWNO { get; set; }
        public string CSELASTUNITID { get; set; }
        public string CSIGNWASTBID { get; set; }
        public string CSIGNWASTHID { get; set; }
        public string CSIGNWASTTYPE { get; set; }
        public string CSOURCEBILLBID { get; set; }
        public string CSOURCEBILLDATE { get; set; }
        public string CSOURCEBILLHID { get; set; }
        public string CSOURCEMATERIALOID { get; set; }
        public string CSOURCETRANSTYPE { get; set; }
        public string CSOURCETYPE { get; set; }
        public string CSOURCEWASTBID { get; set; }
        public string CSOURCEWASTHID { get; set; }
        public string CSOURCEWASTTRANSTYPE { get; set; }
        public string CSOURCEWASTTYPE { get; set; }
        public string CSRC2BILLBID { get; set; }
        public string CSRC2BILLHID { get; set; }
        public string CSRC2BILLTYPE { get; set; }
        public string CSRC2TRANSTYPE { get; set; }
        public string CSRCMATERIALOID { get; set; }
        public string CSRCMATERIALVID { get; set; }
        public string CSTATEID { get; set; }
        public string CTAXCODEID { get; set; }
        public string CTPLCUSTOMERID { get; set; }
        public string CUNITID { get; set; }
        public string CVENDORID { get; set; }
        public string CVMIVENDERID { get; set; }
        public string DBIZDATE { get; set; }
        public string DDELIVERDATE { get; set; }
        public string DPRODUCEDATE { get; set; }
        public Nullable<int> DR { get; set; }
        public string DVALIDATE { get; set; }
        public Nullable<decimal> FBILLROWFLAG { get; set; }
        public string FLARGESS { get; set; }
        public Nullable<decimal> FTAXTYPEFLAG { get; set; }
        public Nullable<decimal> IDESATYPE { get; set; }
        public Nullable<decimal> NASSISTNUM { get; set; }
        public Nullable<decimal> NBARCODENUM { get; set; }
        public Nullable<decimal> NBDISCOUNTRATE { get; set; }
        public Nullable<decimal> NCALTAXMNY { get; set; }
        public Nullable<decimal> NCHANGESTDRATE { get; set; }
        public Nullable<decimal> NCOSTMNY { get; set; }
        public Nullable<decimal> NCOSTPRICE { get; set; }
        public Nullable<decimal> NCOUNTNUM { get; set; }
        public Nullable<decimal> NGLOBALEXCHGRATE { get; set; }
        public Nullable<decimal> NGLOBALMNY { get; set; }
        public Nullable<decimal> NGLOBALTAXMNY { get; set; }
        public Nullable<decimal> NGROSSNUM { get; set; }
        public Nullable<decimal> NGROUPEXCHGRATE { get; set; }
        public Nullable<decimal> NGROUPMNY { get; set; }
        public Nullable<decimal> NGROUPTAXMNY { get; set; }
        public Nullable<decimal> NITEMDISCOUNTRATE { get; set; }
        public Nullable<decimal> NMNY { get; set; }
        public Nullable<decimal> NNETPRICE { get; set; }
        public Nullable<decimal> NNUM { get; set; }
        public Nullable<decimal> NORIGMNY { get; set; }
        public Nullable<decimal> NORIGNETPRICE { get; set; }
        public Nullable<decimal> NORIGPRICE { get; set; }
        public Nullable<decimal> NORIGTAX { get; set; }
        public Nullable<decimal> NORIGTAXMNY { get; set; }
        public Nullable<decimal> NORIGTAXNETPRICE { get; set; }
        public Nullable<decimal> NORIGTAXPRICE { get; set; }
        public Nullable<decimal> NPIECE { get; set; }
        public Nullable<decimal> NPLANNEDMNY { get; set; }
        public Nullable<decimal> NPLANNEDPRICE { get; set; }
        public Nullable<decimal> NPRICE { get; set; }
        public Nullable<decimal> NQTNETPRICE { get; set; }
        public Nullable<decimal> NQTORIGNETPRICE { get; set; }
        public Nullable<decimal> NQTORIGPRICE { get; set; }
        public Nullable<decimal> NQTORIGTAXNETPRC { get; set; }
        public Nullable<decimal> NQTORIGTAXNETPRICE { get; set; }
        public Nullable<decimal> NQTORIGTAXPRICE { get; set; }
        public Nullable<decimal> NQTPRICE { get; set; }
        public Nullable<decimal> NQTTAXNETPRICE { get; set; }
        public Nullable<decimal> NQTTAXPRICE { get; set; }
        public Nullable<decimal> NQTUNITNUM { get; set; }
        public Nullable<decimal> NSHOULDASSISTNUM { get; set; }
        public Nullable<decimal> NSHOULDNUM { get; set; }
        public Nullable<decimal> NTARENUM { get; set; }
        public Nullable<decimal> NTAX { get; set; }
        public Nullable<decimal> NTAXMNY { get; set; }
        public Nullable<decimal> NTAXNETPRICE { get; set; }
        public Nullable<decimal> NTAXPRICE { get; set; }
        public Nullable<decimal> NTAXRATE { get; set; }
        public Nullable<decimal> NVOLUME { get; set; }
        public Nullable<decimal> NWEIGHT { get; set; }
        public string PK_BATCHCODE { get; set; }
        public string PK_GROUP { get; set; }
        public string PK_MEASWARE { get; set; }
        public string PK_ORG { get; set; }
        public string PK_ORG_V { get; set; }
        public string PK_PACKSORT { get; set; }
        public string PK_RETURNREASON { get; set; }
        public string PK_SERIALCODE { get; set; }
        public string TS { get; set; }
        public string VBATCHCODE { get; set; }
        public string VBDEF1 { get; set; }
        public string VBDEF10 { get; set; }
        public string VBDEF11 { get; set; }
        public string VBDEF12 { get; set; }
        public string VBDEF13 { get; set; }
        public string VBDEF14 { get; set; }
        public string VBDEF15 { get; set; }
        public string VBDEF16 { get; set; }
        public string VBDEF17 { get; set; }
        public string VBDEF18 { get; set; }
        public string VBDEF19 { get; set; }
        public string VBDEF2 { get; set; }
        public string VBDEF20 { get; set; }
        public string VBDEF3 { get; set; }
        public string VBDEF4 { get; set; }
        public string VBDEF5 { get; set; }
        public string VBDEF6 { get; set; }
        public string VBDEF7 { get; set; }
        public string VBDEF8 { get; set; }
        public string VBDEF9 { get; set; }
        public string VBILLBARCODE { get; set; }
        public string VBILLTYPEU8RM { get; set; }
        public string VCHANGERATE { get; set; }
        public string VEXIGENCYBID { get; set; }
        public string VEXIGENCYCODE { get; set; }
        public string VEXIGENCYHID { get; set; }
        public string VEXIGENCYROWNO { get; set; }
        public string VFIRSTBILLCODE { get; set; }
        public string VFIRSTROWNO { get; set; }
        public string VFREE1 { get; set; }
        public string VFREE10 { get; set; }
        public string VFREE2 { get; set; }
        public string VFREE3 { get; set; }
        public string VFREE4 { get; set; }
        public string VFREE5 { get; set; }
        public string VFREE6 { get; set; }
        public string VFREE7 { get; set; }
        public string VFREE8 { get; set; }
        public string VFREE9 { get; set; }
        public string VNOTEBODY { get; set; }
        public string VPICKDETAILBID { get; set; }
        public string VPICKDETAILROWNO { get; set; }
        public string VQTUNITRATE { get; set; }
        public string VRECEIVEADDRESS { get; set; }
        public string VSERIALCODE { get; set; }
        public string VSIGNWASTCODE { get; set; }
        public string VSIGNWASTROWNO { get; set; }
        public string VSOURCEBILLCODE { get; set; }
        public string VSOURCEROWNO { get; set; }
        public string VSOURCEWASTCODE { get; set; }
        public string VSOURCEWASTROWNO { get; set; }
        public string VSRC2BILLCODE { get; set; }
        public string VSRC2BILLROWNO { get; set; }
        public string VTRANSFERCODE { get; set; }
        public string VTRANSTYPEU8RM { get; set; }
        public string VVEHICLECODE { get; set; }
    }
}
